FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app

COPY pom.xml ./pom.xml
COPY shared_model/pom.xml ./shared_model/pom.xml
COPY my_stream/pom.xml ./my_stream/pom.xml

RUN mvn install -N -q

COPY shared_model ./shared_model
RUN cd shared_model && mvn clean install -Dmaven.test.skip=true -q

RUN cd my_stream && mvn dependency:go-offline -q

COPY my_stream ./my_stream
RUN cd my_stream && mvn clean package -Dmaven.test.skip=true

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/my_stream/target/my_stream-1.0-SNAPSHOT-jar-with-dependencies.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]