{
  "type": "record",
  "name": "StatusMessage",
  "namespace": "com.weather.model",
  "fields": [
    {
      "name": "station_id",
      "type": "long"
    },
    {
      "name": "s_no",
      "type": "long"
    },
    {
      "name": "battery_status",
      "type": "string"
    },
    {
      "name": "status_timestamp",
      "type": "long"
    },
    {
      "name": "weather",
      "type": {
        "type": "record",
        "name": "WeatherReading",
        "fields": [
          {
            "name": "humidity",
            "type": "int"
          },
          {
            "name": "temperature",
            "type": "int"
          },
          {
            "name": "wind_speed",
            "type": "int"
          }
        ]
      }
    }
  ]
}